spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ***
    type: com.alibaba.druid.pool.DruidDataSource

#=====================druid数据源其他配置,需要被配置类DruidConfig读取否则不生效========================

    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句。
    validationQuery: SELECT 1 FROM DUAL
    # 建议配置为true，不影响性能，并且保证安全性。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，开启会降低性能。
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，开启会降低性能。
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，必须加入log4j依赖
    filters: stat,wall,log4j
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法
  type-aliases-package: com.lee.bean
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
