spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.lee.bean
  mapper-locations: classpath:mapper/*.xml
